# 数据库配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://${maven_docker.ip}:3306/auth?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Ytsy3113678AB
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      validationQuery: SELECT 1 FROM DUAL
      validationQueryTimeout: 30
      initialSize: 10
      minIdle: 10
      maxActive: 200
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100
#redis配置
  redis:
    database: 0
    host: ${maven_docker.ip}
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

#  开启flyway
  flyway:
    enabled: true
    url: jdbc:mysql://${maven_docker.ip}:3306/auth?useUnicode=true&characterEncoding=utf-8
    encoding: UTF-8
    user: root
    password: Ytsy3113678AB
    clean-disabled: true
    schemas: auth

# oauth配置

# 日志
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    com.chery: DEBUG
